site_name: GitHub Metrics
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs

plugins:
  - search
  - charts:
      fences: true  # This enables the chart renderi

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.details
