site_name: GitHub Metrics
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs

plugins:
  - search
  - charts:
      chart_script: true  # Required for chart rendering
      chart_fences: true  # Required for fence blocks

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.details
