name: Deploy
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install mkdocs==1.4.2 mkdocs-material==9.1.8 mkdocs-charts-plugin==1.9.0
      - run: mkdocs gh-deploy --force
