name: Deploy
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install mkdocs mkdocs-material mkdocs-charts-plugin
      - run: mkdocs gh-deploy --force
